// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADNgqgK19JxXdawvu1-VSv8QcbnuQa6AE',
    appId: '1:626479514348:web:8413ab7de1a9352801dbc9',
    messagingSenderId: '626479514348',
    projectId: 'bisimo-usu',
    authDomain: 'bisimo-usu.firebaseapp.com',
    storageBucket: 'bisimo-usu.firebasestorage.app',
    measurementId: 'G-NNY2QV50VX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBruJ1gQ00Avee2zgv_OPPC2CGxGD382gE',
    appId: '1:626479514348:android:6c142711ad1c467f01dbc9',
    messagingSenderId: '626479514348',
    projectId: 'bisimo-usu',
    storageBucket: 'bisimo-usu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYnTf7y8FnFypvKMcOd0goKAtkX-AkMds',
    appId: '1:626479514348:ios:4ebc50376f74ffcd01dbc9',
    messagingSenderId: '626479514348',
    projectId: 'bisimo-usu',
    storageBucket: 'bisimo-usu.firebasestorage.app',
    iosBundleId: 'com.example.bisimo',
  );
}
